name: release
on:
  workflow_dispatch:
    inputs:
      version:
        type: choice
        description: Version number to increment
        required: true
        default: minor
        options:
          - patch
          - minor
          - major

jobs:
  release:
    env:
      CI: true
      GITHUB_TOKEN: ${{ secrets.ACTION_GITHUB_TOKEN }}
      NPM_OTP_TOKEN: ${{ github.event.inputs.otp }}
      NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0 # Need history for changelog generation
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.2
          cache: pnpm
      - run: pnpm i
      - name: types
        run: pnpm run check:types
      - name: build
        run: pnpm run build
      - name: test
        id: test
        if: ${{ always() }}
        run: pnpm run test --coverage
      - name: lint
        if: ${{ always() }}
        run: pnpm run lint
      - name: style
        if: ${{ always() }}
        run: pnpm run format:check
      - name: npm auth
        run: pnpm set "//registry.npmjs.org/:_authToken" ${{ env.NPM_TOKEN }}
      - name: config git user
        run: |
          git config --global user.name ${{ secrets.ACTION_GITHUB_USERNAME }};
          git config --global user.email ${{ secrets.ACTION_GITHUB_EMAIL }};
      - name: perform release
        run: |
          pnpm run release \
            ${{ github.event.inputs.version }} \
            --ci
      - name: codecov # Perform after version publishing
        if: steps.test.outcome == 'success'
        uses: codecov/codecov-action@v5
